name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.9.0
      with:
        host: 'windows'
        arch: 'win64_mingw81'
    - name: qmake
      run: qmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
